name: MCQOL
version: "1.0"
api-version: 1.16
main: io.github.Inspirateur.MCQOL.Main
author: Inspirateur
description: Plugin with various Quality Of Life improvement
commands:
  suicide:
    description: literally kills you.
    usage: /suicide
  pacifist:
    description: join or leave the pacifist category, disabling hurting between you and any other player
    usage: /pacifist true|false
  rain:
    description: allow or disable rain
    usage: /rain true|false
